language: generic

sudo: required

services:
  - docker

before_install:
  - echo "deplay docker hub and aws"

after_success:
  - docker build -t dreamsctv/docker-backend ./backend
  - docker build -t dreamsctv/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push dreamsctv/docker-backend
  - docker push dreamsctv/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'node-crawler'
  env: 'NodeCrawler-env'
  bucket_name: elasticbeanstalk-ap-northeast-1-856304157938
  bucket_path: 'node-crawler'
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
